name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: 2.0.0-rc.1

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test

      - name: Type Check
        run: deno check **/*.ts
